version: '3'
services:

  httpd:
    image: nginx:alpine
    restart: always
    ports: 
      - "80:80"
      - "443:443"
    volumes:
      - ./sslkeys/fullchain.pem:/sslkeys/fullchain.pem:ro
      - ./sslkeys/privkey.pem:/sslkeys/privkey.pem:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./web:/usr/share/nginx/html
    links:
      - php
    depends_on:
      - php
      - sql

  php:
    build:
      context: .
      dockerfile: dockerfiles/php.Dockerfile
    restart: always
    volumes:
      - ./php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./web:/usr/share/nginx/html
    links:
      - sql

  sql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: passwd
      MYSQL_USER: user
      MYSQL_USER_PASSWORD: passwd
      MYSQL_DATABASE: default_db
    volumes:
      - ./sql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: sql
    links:
      - sql
    depends_on:
      - sql
